#! /usr/bin/env python3

import argparse
import time
import random
import pyautogui
from selenium import webdriver

def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
            prog='slowlenium',
            description='Load sets of links sequentially, with some delays',
            epilog='Author: Steve Nolan - 2024')
    #parser.add_argument("--input_file", type=argparse.FileType("r"), help="Input file (of links to be processed)", required=True)
    parser.add_argument("--input_file", help="Input file (of links to be processed)", required=True)
    return parser.parse_args()


def initialize_driver() -> webdriver.Chrome:
    options = webdriver.ChromeOptions()
    options.add_experimental_option("useAutomationExtension", False)
    options.add_experimental_option("excludeSwitches", ["enable-automation"])
    driver = webdriver.Chrome(options=options)
    driver.maximize_window()
    return driver

def install_vimium(driver):
    driver.get("https://chromewebstore.google.com/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb?hl=en")

    time.sleep(1)
    pyautogui.press('tab', presses=10)
    time.sleep(1)
    pyautogui.press('enter', presses=1)
    time.sleep(1)
    pyautogui.press('tab', presses=1)
    time.sleep(1)
    pyautogui.press('enter', presses=1)
    time.sleep(5)
    pyautogui.press('tab', presses=1)
    time.sleep(1)
    pyautogui.press('enter', presses=1)
    time.sleep(1)

def install_ublock_origin(driver):
    driver.get(" https://chromewebstore.google.com/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=en")

    time.sleep(5)
    pyautogui.press('tab', presses=9)
    time.sleep(1)
    pyautogui.press('enter', presses=1)
    time.sleep(1)
    pyautogui.press('tab', presses=1)
    time.sleep(1)
    pyautogui.press('enter', presses=1)
    time.sleep(5)
    pyautogui.press('tab', presses=1)
    time.sleep(1)
    pyautogui.press('enter', presses=1)
    time.sleep(1)

def process_links(driver, link_set):
    with open(link_set) as links:
        for link in links:
            # TODO factor out magic numbers here
            time.sleep(random.randint(0,2))
            driver.switch_to.new_window("tab")
            print(f"Loading: {link.rstrip()}...")
            try:
                driver.get(link)
                print(f"Loaded: {link.rstrip()}.")
                pyautogui.press('tab', presses=4)
            # Connection refused, etc
            except Exception as e:
                print(f"Encountered error:\n{e}")
                pass
            time.sleep(1)

def wait_indefinitely(driver):
    while True:
        time.sleep(86400)

def main():

    args = parse_arguments()
    driver = initialize_driver()
    #install_vimium(driver)
    #install_ublock_origin(driver)
    process_links(driver, args.input_file)
    wait_indefinitely(driver)
    driver.quit()

if __name__ == "__main__":
    main()
